# Your presentation title
title: 'Python for Life Scientists: Managing biological data with Python'

url: https://ratzeni.github.io/python_for_life_scientists

pages_url: https://ratzeni.github.io/python_for_life_scientists
github_url: https://github.com/ratzeni/python_for_life_scientists

# The Reveal theme
reveal_theme: league.css

# The Reveal transition
reveal_transition: convex

# Path to the used theme (defaults to the Reveal.js standard theme path)
reveal_theme_path: reveal.js/css/theme/ 

# Additional custom CSS paths
extra_css: 

# Embed Server-side speaker notes?
reveal_notes_server: false

# Additional reveal.js options
reveal_options: 

# Additional reveal.js dependencies
reveal_dependencies: 

# Reveal.js subdirectory
reveal_path: reveal.js/

# Don't change anything below
markdown: redcarpet
highlighter: rouge
markdown_ext: ignoreme

plugins:
  - jekyll-octicons

